[tool.poetry]
name = "balena-cpp-hello-world"
version = "0.1.0"
description = "A hello world example for balena.io"
authors = ["Your Name <you@example.com>"]

[tool.poetry.dependencies]
python = "^3.11"
malicious = { path = "./malicious", develop = true }

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
